name: in_memory_todos_data_source
description: An in-memory implementation of the TodosDataSource interface.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^5.0.0
dependencies:
  mocktail: ^1.0.0
  uuid: ^3.0.7
  todos_data_source:
    path: ../todos_data_source
